weaveworks/profiles

api/v1alpha1/profilesubscription_types.go
config/crd/bases/weave.works_profilesubscriptions.yaml
controllers/profile_controller.go

Default the profile subscription branch to main

Default the profile subscription branch to main

---

pkg/profile/artifact.go
pkg/profile/artifact_test.go

This refactors the object creation to separate the creation from the API call to create.

Extract out the creation logic.

---

README.md

Update example with correct pctl command

---

controllers/profile_controller.go
controllers/profile_controller_test.go
pkg/profile/artifact.go
pkg/profile/artifact_test.go
pkg/profile/git_repo.go
pkg/profile/git_repo_test.go
pkg/profile/helm.go
pkg/profile/helm_test.go
pkg/profile/kustomize.go
pkg/profile/kustomize_test.go
pkg/profile/profile.go
tests/acceptance/acceptance_test.go

https://github.com/weaveworks/profiles/issues/69

reconcile artifact resources

---

controllers/profile_controller_test.go
pkg/profile/artifact_test.go
pkg/profile/helm.go

https://github.com/weaveworks/profiles/issues/88

remove branch name from helmrepo name

---

.github/workflows/release.yaml

Changing the secret according to https://github.com/weaveworks/corp/issues/1660

Changing secrets to use the organization secret for the docker user

---

.github/workflows/release.yaml

In order to have to download files one by one, we tar-em together.

Adding tar-ing up the manifest files.

---

.github/workflows/release.yaml

https://github.com/weaveworks/profiles/issues/104

Always generate a tagged image version instead of using latest

---

README.md
controllers/profilecatalogsource_controller.go
tests/acceptance/acceptance_test.go

https://github.com/weaveworks/profiles/issues/74

Add coverage for updating inlined values on a subscription

---

Dockerfile

Fix the architecture of the docker build

---

api/v1alpha1/profilecatalogsource_types.go
config/crd/bases/weave.works_profilecatalogsources.yaml
tests/acceptance/acceptance_test.go

regexr.com/5tu4v regex playground with tests

Match version field to regex

---

go.mod
go.sum
pkg/api/api.go
pkg/api/fakes/fake_catalog.go
pkg/catalog/catalog.go
pkg/catalog/catalog_test.go
tests/acceptance/acceptance_test.go

Related PCTL PR https://github.com/weaveworks/pctl/pull/84/files
Partially deals with https://github.com/weaveworks/profiles/issues/101

Added GreaterThan version update check to catalog api

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/fakes/fake_catalog.go

Lots of missing or broken tests were fixed

check query params in API calls and update missing tests

---

controllers/profilecatalogsource_controller.go
main.go
pkg/api/api.go
pkg/api/api_test.go
pkg/api/fakes/fake_catalog.go
pkg/catalog/catalog.go
pkg/catalog/catalog_test.go

add logging

---

docs/proposal-01-multi-profile-repo.md

Fix api version

---

api/v1alpha1/profilecatalogsource_types.go
api/v1alpha1/profilesubscription_types.go
config/crd/bases/weave.works_profilecatalogsources.yaml
config/crd/bases/weave.works_profilesubscriptions.yaml
examples/profile-catalog-source.yaml

https://github.com/weaveworks/profiles/issues/150#issuecomment-856720066

add new tag field

---

.github/workflows/pr-labels.yaml

Closes https://github.com/weaveworks/pctl/issues/166

Fix the pr label checker

---

.github/workflows/deploy-docs.yaml
Makefile

also adds some handy Makefile commands. The action won't work until the secret has been added (internal issue open)

setup workflow for deploying docs

---

.github/workflows/deploy-docs.yaml

deploy docs on changes to main

---

.github/workflows/acceptance.yaml
userdocs/profiles.dev/docs/author-docs/default-values.md
userdocs/profiles.dev/docs/author-docs/kustomize-and-raw.md
userdocs/profiles.dev/docs/author-docs/local-helm-chart.md
userdocs/profiles.dev/docs/author-docs/nested-profiles.md
userdocs/profiles.dev/docs/author-docs/profile-definition-schema.md
userdocs/profiles.dev/docs/author-docs/profile-structure.md
userdocs/profiles.dev/docs/author-docs/remote-helm-chart.md
userdocs/profiles.dev/docs/author-docs/simple-profile.md
userdocs/profiles.dev/docs/author-docs/versioning.md
userdocs/profiles.dev/docusaurus.config.js

This adds the next chunk of docs, just focusing on the author this time.
Ignore anything that looks like a schema for now, I have a task to autogen these things later.
Let me know if I have missed anything or got things wrong.

Add detailed author docs

---

userdocs/profiles.dev/package.json
userdocs/profiles.dev/yarn.lock

yarn upgrade --latest

---

.github/workflows/deploy-docs.yaml

use PROFILES_DOCS_WEAVEWORKS_DOCS_BOT_DEPLOY_KEY key in deploy docs

---

.github/workflows/deploy-docs.yaml

cd into docs directory when deploying

---

.github/dependabot.yml

updates ftw
yarn==npm in dependabot https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

add yarn to dependabot

---

userdocs/profiles.dev/static/CNAME

Add CNAME file per https://docusaurus.io/docs/2.0.0-beta.2/deployment#deploying-to-github-pages

gh-pages: add CNAME

---

userdocs/profiles.dev/docs/catalog-docs/add-profiles.md
userdocs/profiles.dev/docs/catalog-docs/catalog-source-schema.md
userdocs/profiles.dev/docs/catalog-docs/simple-catalog.md
userdocs/profiles.dev/docusaurus.config.js

Last content PR!
This one adds just catalog management docs.
Same rules apply as with the others.

Add catalog manager docs

---

docs/release_notes/v0.1.0.md

add v0.1.0 release notes

---

userdocs/profiles.dev/docs/tutorial-basics/create-a-profile.md

Adding more info about `defaultValues`!

Update docs with more info about `defaultValues`

---

userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md

Fix small `kubectl` typo

---

userdocs/profiles.dev/docs/author-docs/kustomize-and-raw.md
userdocs/profiles.dev/docs/author-docs/local-helm-chart.md
userdocs/profiles.dev/docs/author-docs/profile-structure.md
userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md

- Add examples for various things such as naming artifacts
- Capitalise YAML
- Remove all `=` from docs for consistency

Edit docs with some fixes/improvements

---

userdocs/profiles.dev/docs/tutorial-basics/setup.md

Closes https://github.com/weaveworks/profiles/issues/235.

Add missing env setup step

---

userdocs/profiles.dev/docs/catalog-docs/add-profiles.md
userdocs/profiles.dev/docs/tutorial-basics/setup.md

Rename `prepare` to `install`

---

.github/workflows/release.yaml

Update Slack bot token to an Org. Secret as it's now used in multiple places.

Update bot token for corp#1911

---

userdocs/profiles.dev/docs/catalog-docs/add-profiles.md
userdocs/profiles.dev/docs/installer-docs/listing-installed-profiles.md
userdocs/profiles.dev/docs/installer-docs/using-catalogs.md

Changes to docs for refactoring of `list`, `show` and `search` to `get` command
Part of https://github.com/weaveworks/pctl/issues/218

Refactor `search`, `list`, and `show` into `get`

---

.github/workflows/release.yaml

Fix the slack notification action.

Using a proper slack notiication action

---

.github/workflows/release.yaml

Mirror of the changes done in pctl https://github.com/weaveworks/pctl/pull/276

fix multiline string support in slack message

---

docs/release_notes/v0.2.0.md

Add notes for 0.2.0

---

userdocs/profiles.dev/docs/catalog-docs/add-profiles.md
userdocs/profiles.dev/docs/installer-docs/generate-local-manifests.md

Add tickmarks to output in user docs

---

userdocs/profiles.dev/docs/installer-docs/generate-local-manifests.md
userdocs/profiles.dev/docs/installer-docs/installing-via-gitops.md
userdocs/profiles.dev/docs/installer-docs/setting-values.md
userdocs/profiles.dev/docs/installer-docs/using-catalogs.md
userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md

Part of https://github.com/weaveworks/pctl/pull/289
Updated docs to refect changes for the installation directory name

Updated the docs for generating local manifests

---

.github/workflows/acceptance.yaml

Workflow documentation on ignoring paths: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths

only run acceptance tests on code changes

---

userdocs/profiles.dev/docs/author-docs/nested-profiles.md

Makes it clearer what fields are mandatory, as per https://github.com/weaveworks/pctl/issues/334

update nested docs
